In [1]:
############################################
##################  PCA  ###################
############################################


# When there are lot of variables aka features n(> 10) , then we are advised to do PCA. PCA is a statistical 
# technique which reduces the dimensions of the data and help us understand, plot the data with lesser 
# dimension compared to original data. As the name says PCA helps us compute the Principal components in data. 
# Principal components are basically vectors that are linearly uncorrelated and have a variance with in data.

In [56]:
import matplotlib.pyplot as plt      # import needed packages
import numpy as np 
import pandas as pd
import matplotlib
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn import decomposition
from sklearn.preprocessing import StandardScaler
import seaborn as sns
sns.set()

In [60]:
boston=load_boston()     # load boston dataset
boston_df=pd.DataFrame(boston.data,columns=boston.feature_names)
#print(boston_df.head(3))
boston_df['Price']=boston.target
Y = boston_df['Price']
X = boston_df.drop('Price',axis=1)    # independent variables (predictors)
X = StandardScaler().fit_transform(X)
X = pd.DataFrame(X)

In [61]:
X.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,-0.419782,0.284830,-1.287909,-0.272599,-0.144217,0.413672,-0.120013,0.140214,-0.982843,-0.666608,-1.459000,0.441052,-1.075562
1,-0.417339,-0.487722,-0.593381,-0.272599,-0.740262,0.194274,0.367166,0.557160,-0.867883,-0.987329,-0.303094,0.441052,-0.492439
2,-0.417342,-0.487722,-0.593381,-0.272599,-0.740262,1.282714,-0.265812,0.557160,-0.867883,-0.987329,-0.303094,0.396427,-1.208727
3,-0.416750,-0.487722,-1.306878,-0.272599,-0.835284,1.016303,-0.809889,1.077737,-0.752922,-1.106115,0.113032,0.416163,-1.361517
4,-0.412482,-0.487722,-1.306878,-0.272599,-0.835284,1.228577,-0.511180,1.077737,-0.752922,-1.106115,0.113032,0.441052,-1.026501

In [62]:
pca = decomposition.PCA(n_components=3)
pca.fit(X)
XX = pca.transform(X)

In [64]:
XX.shape
principal_components = pd.DataFrame(data = XX, columns = ['principal component 1', 'principal component 2',
                                                          'principal component 3'])

# concat principal components with target (Y)
principal_components.head()
final = pd.concat([principal_components, Y], axis = 1)

In [66]:
final.head()

   principal component 1  principal component 2  principal component 3  Price
0              -2.098297               0.773113               0.342943   24.0
1              -1.457252               0.591985              -0.695199   21.6
2              -2.074598               0.599639               0.167122   34.7
3              -2.611504              -0.006871              -0.100284   33.4
4              -2.458185               0.097712              -0.075348   36.2